queueMode =  {
    'RANKED_SOLO_5x5': 'Solo Queue',
    'RANKED_FLEX_SR': 'Summoner\'s Rift Flex',
    'RANKED_TFT': 'Teamfight Tactics',
    'RANKED_FLEX_TT': 'Twisted Treeline Flex'
}

rank = {
    'CHALLENGER': 'Challenger',
    'GRANDMASTER':  'Grandmaster',
    'MASTER': 'Master',
    'DIAMOND': 'Diamond',
    'PLATINUM':  'Platinum',
    'GOLD': 'Gold',
    'SILVER': 'Silver',
    'BRONZE': 'Bronze',
    'IRON': 'Iron',
}

queueId = {
    '0': 'Custom Game',
    '72': '1v1 Snowdown Showdown',
    '73': '2v2 Snowdown Showdown',
    '75': 'Hexakill',
    '78': 'One For All: Howling Abyss',
    '100': 'ARAM Butcher\'s Bridge',
    '310': 'Nemesis Draft',
    '400': 'Summoner\'s Rift Draft',
    '420': 'Summoner\'s Rift Ranked Solo/Duo',
    '430': 'Summoner\'s Rift Normal',
    '440': 'Summoner\'s Rift Ranked Flex',
    '450': 'ARAM Howling Abyss',
    '460': 'Twisted Treeline Normal',
    '470': 'Twisted Treeline Ranked Flex',
    '600': 'Blood Hunt',
    '610': 'Dark Star Singularity',
    '700': 'Clash',
    '800': 'Twisted Twisted Co-op vs. AI Intermediate',
    '810': 'Twisted Twisted Co-op vs. AI Intro',
    '820': 'Twisted Twisted Co-op vs. AI Beginner',
    '830': 'Summoner\'s Rift Co-op vs. AI Intro',
    '840': 'Summoner\'s Rift Co-op vs. AI Beginner',
    '850': 'Summoner\'s Rift Co-op vs. AI Intermediate',
    '900': 'ARURF',
    '920': 'Legend of the Poro King',
    '940': 'Nexus Siege',
    '950': 'Doom Bots',
    '960': 'Doom Bots',
    '980': 'Star Guardian Invasion Normal',
    '990': 'Star Guardian Invasion Onslaught',
    '1000': 'PROJECT: Hunters',
    '1020': 'One For All: Summoner\'s Rift',
    '1030': 'Odyssey Extraction Intro',
    '1040': 'Odyssey Extraction Cadet',
    '1050': 'Odyssey Extraction  Crewmember',
    '1060': 'Odyssey Extraction Captain',
    '1070': 'Odyssey Extraction Onslaught',
    '1090': 'Teamfight Tactics Normal',
    '1100': 'Teamfight Tactics Ranked'

}

champs = {
    '266': 'Aatrox',
    '103': 'Ahri',
    '84': 'Akali',
    '12': 'Alistar',
    '32': 'Amumu',
    '34': 'Anivia',
    '1': 'Annie',
    '22': 'Ashe',
    '136': 'AurelionSol',
    '268': 'Azir',
    '432': 'Bard',
    '53': 'Blitzcrank',
    '63': 'Brand',
    '201': 'Braum',
    '51': 'Caitlyn',
    '164': 'Camille',
    '69': 'Cassiopeia',
    '31': 'Chogath',
    '42': 'Corki',
    '122': 'Darius',
    '131': 'Diana',
    '119': 'Draven',
    '36': 'DrMundo',
    '245': 'Ekko',
    '60': 'Elise',
    '28': 'Evelynn',
    '81': 'Ezreal',
    '9': 'Fiddlesticks',
    '114': 'Fiora',
    '105': 'Fizz',
    '3': 'Galio',
    '41': 'Gangplank',
    '86': 'Garen',
    '150': 'Gnar',
    '79': 'Gragas',
    '104': 'Graves',
    '120': 'Hecarim',
    '74': 'Heimerdinger',
    '420': 'Illaoi',
    '39': 'Irelia',
    '427': 'Ivern',
    '40': 'Janna',
    '59': 'JarvanIV',
    '24': 'Jax',
    '126': 'Jayce',
    '202': 'Jhin',
    '222': 'Jinx',
    '145': 'Kaisa',
    '429': 'Kalista',
    '43': 'Karma',
    '30': 'Karthus',
    '38': 'Kassadin',
    '55': 'Katarina',
    '10': 'Kayle',
    '141': 'Kayn',
    '85': 'Kennen',
    '121': 'Khazix',
    '203': 'Kindred',
    '240': 'Kled',
    '96': 'KogMaw',
    '7': 'Leblanc',
    '64': 'LeeSin',
    '89': 'Leona',
    '127': 'Lissandra',
    '236': 'Lucian',
    '117': 'Lulu',
    '99': 'Lux',
    '54': 'Malphite',
    '90': 'Malzahar',
    '57': 'Maokai',
    '11': 'MasterYi',
    '21': 'MissFortune',
    '62': 'MonkeyKing',
    '82': 'Mordekaiser',
    '25': 'Morgana',
    '267': 'Nami',
    '75': 'Nasus',
    '111': 'Nautilus',
    '518': 'Neeko',
    '76': 'Nidalee',
    '56': 'Nocturne',
    '20': 'Nunu',
    '2': 'Olaf',
    '61': 'Orianna',
    '516': 'Ornn',
    '80': 'Pantheon',
    '78': 'Poppy',
    '555': 'Pyke',
    '246': 'Qiyana',
    '133': 'Quinn',
    '497': 'Rakan',
    '33': 'Rammus',
    '421': 'RekSai',
    '58': 'Renekton',
    '107': 'Rengar',
    '92': 'Riven',
    '68': 'Rumble',
    '13': 'Ryze',
    '113': 'Sejuani',
    '35': 'Shaco',
    '98': 'Shen',
    '102': 'Shyvana',
    '27': 'Singed',
    '14': 'Sion',
    '15': 'Sivir',
    '72': 'Skarner',
    '37': 'Sona',
    '16': 'Soraka',
    '50': 'Swain',
    '517': 'Sylas',
    '134': 'Syndra',
    '223': 'TahmKench',
    '163': 'Taliyah',
    '91': 'Talon',
    '44': 'Taric',
    '17': 'Teemo',
    '412': 'Thresh',
    '18': 'Tristana',
    '48': 'Trundle',
    '23': 'Tryndamere',
    '4': 'TwistedFate',
    '29': 'Twitch',
    '77': 'Udyr',
    '6': 'Urgot',
    '110': 'Varus',
    '67': 'Vayne',
    '45': 'Veigar',
    '161': 'Velkoz',
    '254': 'Vi',
    '112': 'Viktor',
    '8': 'Vladimir',
    '106': 'Volibear',
    '19': 'Warwick',
    '498': 'Xayah',
    '101': 'Xerath',
    '5': 'XinZhao',
    '157': 'Yasuo',
    '83': 'Yorick',
    '350': 'Yuumi',
    '154': 'Zac',
    '238': 'Zed',
    '115': 'Ziggs',
    '26': 'Zilean',
    '142': 'Zoe',
    '143': 'Zyra'
}





