queueMode =  {
    'RANKED_SOLO_5x5': 'Solo Queue',
    'RANKED_FLEX_SR': 'Summoner\'s Rift Flex',
    'RANKED_TFT': 'Teamfight Tactics',
    'RANKED_FLEX_TT': 'Twisted Treeline Flex'
}

ranks = {
    'CHALLENGER': 'Challenger',
    'GRANDMASTER':  'Grandmaster',
    'MASTER': 'Master',
    'DIAMOND': 'Diamond',
    'PLATINUM':  'Platinum',
    'GOLD': 'Gold',
    'SILVER': 'Silver',
    'BRONZE': 'Bronze',
    'IRON': 'Iron',
}

queueId = {
    '0': 'Custom Game',
    '72': '1v1 Snowdown Showdown',
    '73': '2v2 Snowdown Showdown',
    '75': 'Hexakill',
    '78': 'One For All: Howling Abyss',
    '100': 'ARAM Butcher\'s Bridge',
    '310': 'Nemesis Draft',
    '400': 'Summoner\'s Rift Draft',
    '420': 'Summoner\'s Rift Ranked Solo/Duo',
    '430': 'Summoner\'s Rift Normal',
    '440': 'Summoner\'s Rift Ranked Flex',
    '450': 'ARAM Howling Abyss',
    '460': 'Twisted Treeline Normal',
    '470': 'Twisted Treeline Ranked Flex',
    '600': 'Blood Hunt',
    '610': 'Dark Star Singularity',
    '700': 'Clash',
    '800': 'Twisted Twisted Co-op vs. AI Intermediate',
    '810': 'Twisted Twisted Co-op vs. AI Intro',
    '820': 'Twisted Twisted Co-op vs. AI Beginner',
    '830': 'Summoner\'s Rift Co-op vs. AI Intro',
    '840': 'Summoner\'s Rift Co-op vs. AI Beginner',
    '850': 'Summoner\'s Rift Co-op vs. AI Intermediate',
    '900': 'ARURF',
    '920': 'Legend of the Poro King',
    '940': 'Nexus Siege',
    '950': 'Doom Bots',
    '960': 'Doom Bots',
    '980': 'Star Guardian Invasion Normal',
    '990': 'Star Guardian Invasion Onslaught',
    '1000': 'PROJECT: Hunters',
    '1020': 'One For All: Summoner\'s Rift',
    '1030': 'Odyssey Extraction Intro',
    '1040': 'Odyssey Extraction Cadet',
    '1050': 'Odyssey Extraction  Crewmember',
    '1060': 'Odyssey Extraction Captain',
    '1070': 'Odyssey Extraction Onslaught',
    '1090': 'Teamfight Tactics Normal',
    '1100': 'Teamfight Tactics Ranked'

}

champsById = {
    '266': 'Aatrox',
    '103': 'Ahri',
    '84': 'Akali',
    '12': 'Alistar',
    '32': 'Amumu',
    '34': 'Anivia',
    '1': 'Annie',
    '22': 'Ashe',
    '136': 'Aurelion Sol',
    '268': 'Azir',
    '432': 'Bard',
    '53': 'Blitzcrank',
    '63': 'Brand',
    '201': 'Braum',
    '51': 'Caitlyn',
    '164': 'Camille',
    '69': 'Cassiopeia',
    '31': 'Cho\'Gath',
    '42': 'Corki',
    '122': 'Darius',
    '131': 'Diana',
    '119': 'Draven',
    '36': 'Dr.Mundo',
    '245': 'Ekko',
    '60': 'Elise',
    '28': 'Evelynn',
    '81': 'Ezreal',
    '9': 'Fiddlesticks',
    '114': 'Fiora',
    '105': 'Fizz',
    '3': 'Galio',
    '41': 'Gangplank',
    '86': 'Garen',
    '150': 'Gnar',
    '79': 'Gragas',
    '104': 'Graves',
    '120': 'Hecarim',
    '74': 'Heimerdinger',
    '420': 'Illaoi',
    '39': 'Irelia',
    '427': 'Ivern',
    '40': 'Janna',
    '59': 'JarvanIV',
    '24': 'Jax',
    '126': 'Jayce',
    '202': 'Jhin',
    '222': 'Jinx',
    '145': 'Kai\'Sa',
    '429': 'Kalista',
    '43': 'Karma',
    '30': 'Karthus',
    '38': 'Kassadin',
    '55': 'Katarina',
    '10': 'Kayle',
    '141': 'Kayn',
    '85': 'Kennen',
    '121': 'Kha\'Zix',
    '203': 'Kindred',
    '240': 'Kled',
    '96': 'Kog\'Maw',
    '7': 'Leblanc',
    '64': 'LeeSin',
    '89': 'Leona',
    '127': 'Lissandra',
    '236': 'Lucian',
    '117': 'Lulu',
    '99': 'Lux',
    '54': 'Malphite',
    '90': 'Malzahar',
    '57': 'Maokai',
    '11': 'MasterYi',
    '21': 'Miss Fortune',
    '62': 'Wukong',
    '82': 'Mordekaiser',
    '25': 'Morgana',
    '267': 'Nami',
    '75': 'Nasus',
    '111': 'Nautilus',
    '518': 'Neeko',
    '76': 'Nidalee',
    '56': 'Nocturne',
    '20': 'Nunu',
    '2': 'Olaf',
    '61': 'Orianna',
    '516': 'Ornn',
    '80': 'Pantheon',
    '78': 'Poppy',
    '555': 'Pyke',
    '246': 'Qiyana',
    '133': 'Quinn',
    '497': 'Rakan',
    '33': 'Rammus',
    '421': 'Rek\'Sai',
    '58': 'Renekton',
    '107': 'Rengar',
    '92': 'Riven',
    '68': 'Rumble',
    '13': 'Ryze',
    '113': 'Sejuani',
    '35': 'Shaco',
    '98': 'Shen',
    '102': 'Shyvana',
    '27': 'Singed',
    '14': 'Sion',
    '15': 'Sivir',
    '72': 'Skarner',
    '37': 'Sona',
    '16': 'Soraka',
    '50': 'Swain',
    '517': 'Sylas',
    '134': 'Syndra',
    '223': 'Tahm Kench',
    '163': 'Taliyah',
    '91': 'Talon',
    '44': 'Taric',
    '17': 'Teemo',
    '412': 'Thresh',
    '18': 'Tristana',
    '48': 'Trundle',
    '23': 'Tryndamere',
    '4': 'Twisted Fate',
    '29': 'Twitch',
    '77': 'Udyr',
    '6': 'Urgot',
    '110': 'Varus',
    '67': 'Vayne',
    '45': 'Veigar',
    '161': 'Vel\'Koz',
    '254': 'Vi',
    '112': 'Viktor',
    '8': 'Vladimir',
    '106': 'Volibear',
    '19': 'Warwick',
    '498': 'Xayah',
    '101': 'Xerath',
    '5': 'Xin Zhao',
    '157': 'Yasuo',
    '83': 'Yorick',
    '350': 'Yuumi',
    '154': 'Zac',
    '238': 'Zed',
    '115': 'Ziggs',
    '26': 'Zilean',
    '142': 'Zoe',
    '143': 'Zyra'
}

champsByName = {
    'Aatrox': 266,
    'Ahri': 103,
    'Akali': 84,
    'Alistar': 12,
    'Amumu': 32,
    'Anivia': 34,
    'Annie': 1,
    'Ashe': 22,
    'Aurelion Sol': 136,
    'Azir': 268,
    'Bard': 432,
    'Blitzcrank': 53,
    'Brand': 63,
    'Braum': 201,
    'Caitlyn': 51,
    'Camille': 164,
    'Cassiopeia': 69,
    'Cho\'Gath': 31,
    'Corki': 42,
    'Darius': 122,
    'Diana': 131,
    'Draven': 119,
    'Dr.Mundo': 36,
    'Ekko': 245,
    'Elise': 60,
    'Evelynn': 28,
    'Ezreal': 81,
    'Fiddlesticks': 9,
    'Fiora': 114,
    'Fizz': 105,
    'Galio': 3,
    'Gangplank': 41,
    'Garen': 86,
    'Gnar': 150,
    'Gragas': 79,
    'Graves': 104,
    'Hecarim': 120,
    'Heimerdinger': 74,
    'Illaoi': 420,
    'Irelia': 39,
    'Ivern': 427,
    'Janna': 40,
    'JarvanIV': 59,
    'Jax': 24,
    'Jayce': 126,
    'Jhin': 202,
    'Jinx': 222,
    'Kai\'Sa': 145,
    'Kalista': 429,
    'Karma': 43,
    'Karthus': 30,
    'Kassadin': 38,
    'Katarina': 55,
    'Kayle': 10,
    'Kayn': 141,
    'Kennen': 85,
    "Kha'Zix": 121,
    'Kindred': 203,
    'Kled': 240,
    'Kog\'Maw': 96,
    'Leblanc': 7,
    'LeeSin': 64,
    'Leona': 89,
    'Lissandra': 127,
    'Lucian': 236,
    'Lulu': 117,
    'Lux': 99,
    'Malphite': 54,
    'Malzahar': 90,
    'Maokai': 57,
    'MasterYi': 11,
    'Miss Fortune': 21,
    'Wukong': 62,
    'Mordekaiser': 82,
    'Morgana': 25,
    'Nami': 267,
    'Nasus': 75,
    'Nautilus': 111,
    'Neeko': 518,
    'Nidalee': 76,
    'Nocturne': 56,
    'Nunu': 20,
    'Olaf': 2,
    'Orianna': 61,
    'Ornn': 516,
    'Pantheon': 80,
    'Poppy': 78,
    'Pyke': 555,
    'Qiyana': 246,
    'Quinn': 133,
    'Rakan': 497,
    'Rammus': 33,
    'Rek\'Sai': 421,
    'Renekton': 58,
    'Rengar': 107,
    'Riven': 92,
    'Rumble': 68,
    'Ryze': 13,
    'Sejuani': 113,
    'Shaco': 35,
    'Shen': 98,
    'Shyvana': 102,
    'Singed': 27,
    'Sion': 14,
    'Sivir': 15,
    'Skarner': 72,
    'Sona': 37,
    'Soraka': 16,
    'Swain': 50,
    'Sylas': 517,
    'Syndra': 134,
    'Tahm Kench': 223,
    'Taliyah': 163,
    'Talon': 91,
    'Taric': 44,
    'Teemo': 17,
    'Thresh': 412,
    'Tristana': 18,
    'Trundle': 48,
    'Tryndamere': 23,
    'Twisted Fate': 4,
    'Twitch': 29,
    'Udyr': 77,
    'Urgot': 6,
    'Varus': 110,
    'Vayne': 67,
    'Veigar': 45,
    'Vel\'Koz': 161,
    'Vi': 254,
    'Viktor': 112,
    'Vladimir': 8,
    'Volibear': 106,
    'Warwick': 19,
    'Xayah': 498,
    'Xerath': 101,
    'Xin Zhao': 5,
    'Yasuo': 157,
    'Yorick': 83,
    'Yuumi': 350,
    'Zac': 154,
    'Zed': 238,
    'Ziggs': 115,
    'Zilean': 26,
    'Zoe': 142,
    'Zyra': 143
}

roles = {
    'top' : ['Yorick', 'Yasuo', 'Volibear', 'Vladimir', 'Urgot', 'Tryndamere',
        'Teemo', 'Tahm Kench', 'Sylas', 'Sion', 'Singed', 'Shen', 'Ryze',
        'Rumble', 'Riven', 'Rengar', 'Renekton', 'Quinn', 'Qiyana', 'Poppy',
        'Pantheon', 'Ornn', 'Olaf', 'Neeko', 'Nasus', 'Mordekaiser', 'Maokai',
        'Malphite', 'Kled', 'Kennen', 'Kayle', 'Karma', 'Jayce', 'Jax', 'Irelia',
        'Illaoi', 'Gnar', 'Garen', 'Gangplank', 'Fiora', 'Dr. Mundo', 'Darius',
        'Cho\'Gath', 'Camille', 'Akali', 'Aatrox'],

    'jungle' : ['Zac','Xin Zhao','Wukong','Warwick','Volibear','Vi','Udyr','Twitch',
        'Tryndamere','Trundle','Taliyah','Sylas','Skarner','Shyvana','Shaco','Sejuani',
        'Rengar','Rek\'Sai','Rammus','Qiyana','Pantheon','Olaf','Nunu','Nocturne',
        'Nidalee','Mordekaiser','Master Yi','Lee Sin','Kindred','Kha\'Zix','Kayn',
        'Karthus','Jax','Jarvan IV','Ivern','Hecarim','Graves','Gragas','Fiddlesticks',
        'Evelynn','Elise','Ekko','Camille','Amumu','Aatrox'],

    'mid' : ['Zoe','Ziggs','Zed','Yasuo','Xerath','Vladimir','Viktor','Vel\'Koz',
        'Veigar','Twisted Fate','Talon','Taliyah','Syndra','Sylas','Swain','Ryze',
        'Rumble','Qiyana','Orianna','Neeko','Morgana','Mordekaiser','Malzahar','Lux',
        'Lissandra','LeBlanc','Katarina','Kassadin','Irelia','Fizz','Ekko','Diana',
        'Corki','Cassiopeia','Brand','Azir','Aurelion Sol','Annie','Anivia','Akali',
        'Ahri','Aatrox'],

    'bot' : ['Xayah','Vayne','Varus','Twitch','Tristana','Sivir','Miss Fortune',
        'Lucian','Kog\'Maw','Kalista','Kai\'Sa','Jinx','Jhin','Ezreal','Draven',
        'Caitlyn','Ashe','Yasuo'],

    'support' : ['Zyra','Zilean','Yuumi','Xerath','Vel\'Koz','Veigar','Thresh',
        'Teemo','Taric','Tahm Kench','Soraka','Sona','Shen','Rakan','Pyke','Neeko',
        'Nautilus','Nami','Morgana','Miss Fortune','Malphite','Lux','Lulu','Leona',
        'Karma','Janna','Galio','Fiddlesticks','Braum','Brand','Blitzcrank','Bard',
        'Ashe','Alistar']
}



